alias: 'Tal vez entre/salga alguien'
trigger:
  platform: state
  entity_id: binary_sensor.puertaentrada_1_0
  from: 'on'
  to: 'off'
condition:
  - condition: state
    entity_id: group.familia
    state: 'home'
action:
  service: homeassistant.turn_on
  entity_id: script.buscagente
