alias: 'Alguien entra'
trigger:
  platform: state
  entity_id: binary_sensor.puertaentrada_1_0
  to: 'on'
condition:
  - condition: state
    entity_id: group.familia
    state: 'not_home'
action:
  service: homeassistant.turn_on
  entity_id: script.buscagente
