alias: 'Apaga Luces Mañana (Entre semana)'
trigger:
  platform: time
  after: '08:30'
condition:
  - condition: state
    entity_id: group.all_lights
    state: 'on'
  - condition: time
    weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
action:
  service: script.turn_on
  entity_id: script.apagaluces
