alias: 'Despertador'
trigger:
  platform: template
  value_template: '{{ now.time().strftime("%H:%M") == states.input_select.alarma_cuarto.state }}'
condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: state
    entity_id: input_boolean.despcuarto
    state: 'on'
  - condition: state
    entity_id: group.familia
    state: 'home'
action:
  service: scene.turn_on
  entity_id: scene.despiertacuarto
