alias: 'Luces Tarde (Finde)'
trigger:
  platform: numeric_state
  entity_id: sun.sun
  value_template: '{{ state.attributes.elevation }}'
  below: 6
condition:
  - condition: state
    entity_id: input_boolean.luztarde
    state: 'on'
  - condition: time
    weekday:
      - sat
      - sun
action:
  service: scene.turn_on
  data_template:
    entity_id: "{%if states.group.familia.state == 'home' %}scene.tarde{% else %}scene.noche{% endif %}"
