alias: 'Para de buscar'
trigger:
  platform: state
  entity_id: group.familia
  from: 'not_home'
  to: 'home'
action:
  - service: homeassistant.turn_off
    entity_id: script.buscagente
  - service: homeassistant.turn_off
    entity_id: input_boolean.vacaciones
