alias: 'Saliendo de casa: Apaga Luces'
trigger:
  platform: state
  entity_id: group.familia
  from: 'home'
  to: 'not_home'
condition:
  condition: time
  after: '06:00'
  before: '09:00'
action:
  service: script.turn_on
  entity_id: script.apagaluces
