alias: 'Vacaciones 1'
trigger:
  platform: time
  after: '09:00'
condition:
  - condition: state
    entity_id: group.familia
    state: 'not_home'
  - condition: state
    entity_id: input_boolean.vacaciones
    state: 'on'
action:
  - service: homeassistant.turn_on
    entity_id: switch.radio
  - delay:
      minutes: 30
  - service: homeassistant.turn_off
    entity_id: switch.radio
